onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/sys_clk_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/per_clk_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/dft_cg_enable_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/HRESETn
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PADDR
add wave -noupdate -group i_udmacore -radix hexadecimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PWDATA
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PWRITE
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PSEL
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PENABLE
add wave -noupdate -group i_udmacore -radix hexadecimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PRDATA
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PREADY
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PSLVERR
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/event_valid_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/event_data_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/event_ready_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/event_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_per_clk_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_sys_clk_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_data_to_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_addr_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_rwn_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_data_from_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_valid_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_ready_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_l2_req_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_l2_gnt_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_l2_addr_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_l2_be_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_l2_wdata_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_l2_req_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_l2_gnt_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_l2_addr_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_l2_rdata_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_l2_rvalid_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/stream_data_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/stream_datasize_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/stream_valid_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/stream_sot_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/stream_eot_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/stream_ready_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_valid_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_data_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_datasize_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_destination_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_ready_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_events_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_en_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_pending_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_curr_addr_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_bytes_left_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_cfg_startaddr_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_cfg_size_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_cfg_continuous_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_cfg_en_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_cfg_stream_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_cfg_stream_id_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_cfg_clr_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_addr_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_datasize_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_destination_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_stream_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_stream_id_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_sot_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_eot_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_valid_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_data_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_ready_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_req_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_gnt_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_valid_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_data_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_ready_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_datasize_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_destination_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_events_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_en_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_pending_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_curr_addr_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_bytes_left_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_cfg_startaddr_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_cfg_size_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_cfg_continuous_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_cfg_en_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_cfg_clr_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_req_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_datasize_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_destination_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_addr_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_gnt_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_valid_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_data_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_ready_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ch_req
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ch_addr
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ch_datasize
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ch_gnt
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ch_valid
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ch_data
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ch_ready
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_cfg_en
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_cfg_addr
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_cfg_buffsize
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_cfg_datasize
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_req
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_datasize
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_dest
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_addr
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_gnt
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_valid
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_data
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_ready
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_events
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_data_to
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_addr
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_rwn
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_data_from
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_valid
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_ready
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_ready_from_cgunit
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_data_from_cgunit
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_cg_value
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_clk_core
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_clk_core_en
add wave -noupdate -group i2s_clk_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/clk_i
add wave -noupdate -group i2s_clk_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/rstn_i
add wave -noupdate -group i2s_clk_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/test_mode_i
add wave -noupdate -group i2s_clk_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/sck_o
add wave -noupdate -group i2s_clk_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/cfg_clk_en_i
add wave -noupdate -group i2s_clk_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/cfg_clk_en_o
add wave -noupdate -group i2s_clk_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/cfg_div_i
add wave -noupdate -group i2s_clk_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/r_counter
add wave -noupdate -group i2s_clk_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/r_clk
add wave -noupdate -group i2s_clk_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/r_sampled_config
add wave -noupdate -group i2s_clk_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/r_clock_en
add wave -noupdate -group i2s_clk_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/clk_i
add wave -noupdate -group i2s_clk_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/rstn_i
add wave -noupdate -group i2s_clk_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/test_mode_i
add wave -noupdate -group i2s_clk_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/sck_o
add wave -noupdate -group i2s_clk_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/cfg_clk_en_i
add wave -noupdate -group i2s_clk_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/cfg_clk_en_o
add wave -noupdate -group i2s_clk_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/cfg_div_i
add wave -noupdate -group i2s_clk_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/r_counter
add wave -noupdate -group i2s_clk_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/r_clk
add wave -noupdate -group i2s_clk_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/r_sampled_config
add wave -noupdate -group i2s_clk_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/r_clock_en
add wave -noupdate -group i2s_ws_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_0/sck_i
add wave -noupdate -group i2s_ws_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_0/rstn_i
add wave -noupdate -group i2s_ws_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_0/cfg_ws_en_i
add wave -noupdate -group i2s_ws_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_0/ws_o
add wave -noupdate -group i2s_ws_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_0/cfg_data_size_i
add wave -noupdate -group i2s_ws_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_0/cfg_word_num_i
add wave -noupdate -group i2s_ws_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_0/r_counter
add wave -noupdate -group i2s_ws_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_0/r_word_counter
add wave -noupdate -group i2s_ws_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_1/sck_i
add wave -noupdate -group i2s_ws_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_1/rstn_i
add wave -noupdate -group i2s_ws_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_1/cfg_ws_en_i
add wave -noupdate -group i2s_ws_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_1/ws_o
add wave -noupdate -group i2s_ws_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_1/cfg_data_size_i
add wave -noupdate -group i2s_ws_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_1/cfg_word_num_i
add wave -noupdate -group i2s_ws_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_1/r_counter
add wave -noupdate -group i2s_ws_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_gen_1/r_word_counter
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/sck_i
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/rstn_i
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/i2s_ch0_o
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/i2s_ch1_o
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/i2s_ws_i
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/fifo_data_i
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/fifo_data_valid_i
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/fifo_data_ready_o
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/fifo_err_o
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/cfg_en_i
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/cfg_2ch_i
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/cfg_wlen_i
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/cfg_wnum_i
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/cfg_lsb_first_i
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/r_ws_sync
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/s_ws_edge
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/r_shiftreg_ch0
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/r_shiftreg_ch1
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/s_shiftreg_ch0
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/s_shiftreg_ch1
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/r_shiftreg_shadow
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/s_shiftreg_shadow
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/s_sample_in
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/s_sample_sr0
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/s_sample_sr1
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/s_sample_swd
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/s_update_cnt
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/r_count_bit
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/r_count_word
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/s_word_done
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/r_started
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/r_state
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/s_state
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/s_word_done_pre
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/s_i2s_ch0
add wave -noupdate -group i2s_tx_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_master/s_i2s_ch1
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/sck_i
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/rstn_i
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/i2s_ch0_i
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/i2s_ch1_i
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/i2s_ws_i
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/fifo_data_o
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/fifo_data_valid_o
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/fifo_data_ready_i
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/fifo_err_o
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/cfg_en_i
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/cfg_2ch_i
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/cfg_wlen_i
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/cfg_wnum_i
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/cfg_lsb_first_i
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/r_ws_old
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/s_ws_edge
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/r_shiftreg_ch0
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/r_shiftreg_ch1
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/s_shiftreg_ch0
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/s_shiftreg_ch1
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/r_shiftreg_ch0_shadow
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/r_shiftreg_ch1_shadow
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/r_count_bit
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/r_word_done_dly
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/s_word_done
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/r_started
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/r_started_dly
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/r_ch0_valid
add wave -noupdate -group i2s_rx_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_slave/r_ch1_valid
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_sd0_i
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_sd1_i
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_sck_i
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_sck_o
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_sck_oe
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_ws_i
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_ws_o
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_ws_oe
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_sd0_o
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_sd1_o
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_sck_i
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_sck_o
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_sck_oe
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_ws_i
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_ws_o
add wave -noupdate -group i2s_top_pad /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_ws_oe
add wave -noupdate -group i2s1_sdi_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s1_sdi/OEN
add wave -noupdate -group i2s1_sdi_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s1_sdi/I
add wave -noupdate -group i2s1_sdi_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s1_sdi/O
add wave -noupdate -group i2s1_sdi_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s1_sdi/PEN
add wave -noupdate -group i2s1_sdi_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s1_sdi/PAD
add wave -noupdate -group i2s1_sdi_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s1_sdi/PAD_wi
add wave -noupdate -group i2s0_sdi_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_sdi/OEN
add wave -noupdate -group i2s0_sdi_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_sdi/I
add wave -noupdate -group i2s0_sdi_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_sdi/O
add wave -noupdate -group i2s0_sdi_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_sdi/PEN
add wave -noupdate -group i2s0_sdi_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_sdi/PAD
add wave -noupdate -group i2s0_sdi_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_sdi/PAD_wi
add wave -noupdate -group i2s0_ws_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_ws/OEN
add wave -noupdate -group i2s0_ws_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_ws/I
add wave -noupdate -group i2s0_ws_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_ws/O
add wave -noupdate -group i2s0_ws_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_ws/PEN
add wave -noupdate -group i2s0_ws_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_ws/PAD
add wave -noupdate -group i2s0_ws_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_ws/PAD_wi
add wave -noupdate -group i2s0_clk_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_sck/OEN
add wave -noupdate -group i2s0_clk_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_sck/I
add wave -noupdate -group i2s0_clk_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_sck/O
add wave -noupdate -group i2s0_clk_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_sck/PEN
add wave -noupdate -group i2s0_clk_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_sck/PAD
add wave -noupdate -group i2s0_clk_tb_pad /tb_pulp/i_dut/pad_frame_i/padinst_i2s0_sck/PAD_wi
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/clk_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/periph_clk_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/rstn_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_data_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_addr_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_valid_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rwn_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_data_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_ready_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_startaddr_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_size_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_datasize_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_continuous_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_en_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_clr_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_en_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_pending_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_curr_addr_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_bytes_left_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_startaddr_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_size_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_datasize_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_continuous_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_en_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_clr_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_en_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_pending_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_curr_addr_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_bytes_left_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_clk_en_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_clk_en_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_pdm_clk_en_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_dsp_en_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_dsp_setup_time_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_dsp_mode_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_sel_num_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_sel_ext_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_sel_num_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_sel_ext_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_i2s_en_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_i2s_lsb_first_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_i2s_2ch_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_i2s_bits_word_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_i2s_words_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_pdm_en_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_pdm_mode_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_pdm_decimation_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_pdm_shift_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_i2s_en_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_i2s_lsb_first_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_i2s_2ch_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_i2s_bits_word_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_i2s_words_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_gen_clk_en_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_gen_clk_en_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_gen_clk_div_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_gen_clk_en_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_gen_clk_en_i
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_gen_clk_div_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_rx_startaddr
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_rx_size
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_rx_datasize
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_rx_continuous
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_rx_en
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_rx_clr
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_tx_startaddr
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_tx_size
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_tx_datasize
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_tx_continuous
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_tx_en
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_tx_clr
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_clk_en
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_clk_en
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_master_clk_en
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_slave_clk_en
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_sel_num
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_sel_ext
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_sel_num
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_sel_ext
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_master_sel_num
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_master_sel_ext
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_slave_sel_num
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_slave_sel_ext
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_i2s_en
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_i2s_lsb_first
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_i2s_2ch
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_i2s_bits_word
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_i2s_words
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_pdm_en
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_pdm_mode
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_pdm_decimation
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_pdm_shift
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_dsp_en
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_dsp_setup_time
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_dsp_mode
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_i2s_en
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_i2s_lsb_first
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_i2s_2ch
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_i2s_bits_word
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_i2s_words
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_common_gen_clk_div
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_gen_clk_div
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_gen_clk_div
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_common_gen_clk_div
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_slave_gen_clk_div
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_master_gen_clk_div
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_pdm_clk_en
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_pdm_clk_en
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/s_wr_addr
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/s_rd_addr
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/s_update_clk
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_update_clk
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_update_clk_o
add wave -noupdate -group i2s_reg /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/s_update
add wave -noupdate -group i2s_dsp_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_gen/sck_i
add wave -noupdate -group i2s_dsp_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_gen/rstn_i
add wave -noupdate -group i2s_dsp_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_gen/cfg_ws_en_i
add wave -noupdate -group i2s_dsp_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_gen/cfg_num_bits_i
add wave -noupdate -group i2s_dsp_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_gen/cfg_num_words_i
add wave -noupdate -group i2s_dsp_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_gen/cfg_dsp_setup_time_i
add wave -noupdate -group i2s_dsp_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_gen/cfg_dsp_mode_i
add wave -noupdate -group i2s_dsp_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_gen/ws_o
add wave -noupdate -group i2s_dsp_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_gen/limit
add wave -noupdate -group i2s_dsp_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_gen/state
add wave -noupdate -group i2s_dsp_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_gen/next_state
add wave -noupdate -group i2s_dsp_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_gen/count
add wave -noupdate -group i2s_dsp_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_gen/set
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/sck_i
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/rstn_i
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/i2s_ch0_i
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/i2s_ch1_i
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/i2s_ws_i
add wave -noupdate -group i2s_dsp_sample -radix unsigned /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/fifo_data_o
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/fifo_data_valid_o
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/fifo_data_ready_i
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/fifo_err_o
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_en_i
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_2ch_i
add wave -noupdate -group i2s_dsp_sample -radix unsigned /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_num_bits_i
add wave -noupdate -group i2s_dsp_sample -radix unsigned /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_num_word_i
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_lsb_first_i
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_rx_continuous_i
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_dsp_mode_i
add wave -noupdate -group i2s_dsp_sample -radix unsigned /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_shiftreg_ch0
add wave -noupdate -group i2s_dsp_sample -radix unsigned /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_shiftreg_ch1
add wave -noupdate -group i2s_dsp_sample -radix unsigned /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_shiftreg_ch0_shadow
add wave -noupdate -group i2s_dsp_sample -radix unsigned /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_shiftreg_ch1_shadow
add wave -noupdate -group i2s_dsp_sample -radix unsigned /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_count_bit
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/start
add wave -noupdate -group i2s_dsp_sample -radix unsigned /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/set_counter
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_ch0_valid
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_ch1_valid
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/state
add wave -noupdate -group i2s_dsp_sample /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/next_state
add wave -noupdate -group generic_dsp_0 /tb_pulp/genblk6/genblk2/generic_dsp_device_0/data
add wave -noupdate -group generic_dsp_0 /tb_pulp/genblk6/genblk2/generic_dsp_device_0/lsb_first
add wave -noupdate -group generic_dsp_0 /tb_pulp/genblk6/genblk2/generic_dsp_device_0/dsp_mode
add wave -noupdate -group generic_dsp_0 /tb_pulp/genblk6/genblk2/generic_dsp_device_0/ws
add wave -noupdate -group generic_dsp_0 /tb_pulp/genblk6/genblk2/generic_dsp_device_0/bclk
add wave -noupdate -group generic_dsp_0 /tb_pulp/genblk6/genblk2/generic_dsp_device_0/dout
add wave -noupdate -group generic_dsp_0 /tb_pulp/genblk6/genblk2/generic_dsp_device_0/wso
add wave -noupdate -group generic_dsp_0 /tb_pulp/genblk6/genblk2/generic_dsp_device_0/state
add wave -noupdate -group generic_dsp_0 /tb_pulp/genblk6/genblk2/generic_dsp_device_0/next_state
add wave -noupdate -group generic_dsp_0 /tb_pulp/genblk6/genblk2/generic_dsp_device_0/count
add wave -noupdate -group generic_dsp_0 /tb_pulp/genblk6/genblk2/generic_dsp_device_0/start
add wave -noupdate -group generic_dsp_0 /tb_pulp/genblk6/genblk2/generic_dsp_device_0/tristate
add wave -noupdate -group generic_dsp_0 /tb_pulp/genblk6/genblk2/generic_dsp_device_0/mode
add wave -noupdate -group generic_dsp_1 /tb_pulp/genblk6/genblk2/generic_dsp_device_1/data
add wave -noupdate -group generic_dsp_1 /tb_pulp/genblk6/genblk2/generic_dsp_device_1/lsb_first
add wave -noupdate -group generic_dsp_1 /tb_pulp/genblk6/genblk2/generic_dsp_device_1/dsp_mode
add wave -noupdate -group generic_dsp_1 /tb_pulp/genblk6/genblk2/generic_dsp_device_1/ws
add wave -noupdate -group generic_dsp_1 /tb_pulp/genblk6/genblk2/generic_dsp_device_1/bclk
add wave -noupdate -group generic_dsp_1 /tb_pulp/genblk6/genblk2/generic_dsp_device_1/dout
add wave -noupdate -group generic_dsp_1 /tb_pulp/genblk6/genblk2/generic_dsp_device_1/wso
add wave -noupdate -group generic_dsp_1 /tb_pulp/genblk6/genblk2/generic_dsp_device_1/state
add wave -noupdate -group generic_dsp_1 /tb_pulp/genblk6/genblk2/generic_dsp_device_1/next_state
add wave -noupdate -group generic_dsp_1 /tb_pulp/genblk6/genblk2/generic_dsp_device_1/count
add wave -noupdate -group generic_dsp_1 /tb_pulp/genblk6/genblk2/generic_dsp_device_1/start
add wave -noupdate -group generic_dsp_1 /tb_pulp/genblk6/genblk2/generic_dsp_device_1/tristate
add wave -noupdate -group generic_dsp_1 /tb_pulp/genblk6/genblk2/generic_dsp_device_1/mode
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {1 ns}
