onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/sys_clk_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/periph_clk_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/rstn_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/dft_test_mode_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/dft_cg_enable_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_sd0_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_sd1_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_sck_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_sck_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_sck_oe
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_ws_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_ws_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_slave_ws_oe
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_sd0_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_sd1_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_sck_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_sck_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_sck_oe
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_ws_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_ws_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/pad_master_ws_oe
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_data_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_addr_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_valid_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_rwn_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_ready_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_data_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_rx_startaddr_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_rx_size_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_rx_continuous_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_rx_en_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_rx_clr_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_rx_en_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_rx_pending_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_rx_curr_addr_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_rx_bytes_left_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_tx_startaddr_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_tx_size_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_tx_continuous_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_tx_en_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_tx_clr_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_tx_en_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_tx_pending_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_tx_curr_addr_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/cfg_tx_bytes_left_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/data_rx_datasize_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/data_rx_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/data_rx_valid_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/data_rx_ready_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/data_tx_req_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/data_tx_gnt_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/data_tx_datasize_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/data_tx_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/data_tx_valid_i
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/data_tx_ready_o
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_mode
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_i2s_mode
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_i2s_lsb_first
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_i2s_bits_word
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_i2s_words
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_pdm_mode
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_pdm_decimation
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_pdm_shift
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_dsp_en
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_dsp_setup_time
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_dsp_mode
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_dsp_offset
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_master_dsp_en
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_master_dsp_setup_time
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_master_dsp_mode
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_master_dsp_offset
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_cfg_rx_continuous
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_master_i2s_mode
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_master_i2s_lsb_first
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_master_i2s_bits_word
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_master_i2s_words
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_gen_clk_eni
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_gen_clk_eno
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_gen_clk_div
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_master_gen_clk_eni
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_master_gen_clk_eno
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_master_gen_clk_div
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_fifo_data
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_fifo_valid
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_fifo_ready
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_data_tx
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_data_tx_valid
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_data_tx_ready
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_data_rx_dc
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_data_rx_dc_valid
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_data_rx_dc_ready
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_data_tx_dc
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_data_tx_dc_valid
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_data_tx_dc_ready
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_cfg_word_size_0
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_cfg_word_num_0
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_cfg_word_size_1
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_cfg_word_num_1
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_sel_master_num
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_sel_master_ext
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_sel_slave_num
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_sel_slave_ext
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_master_clk_en
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_clk_en
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_pdm_clk_en
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_i2s_en
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_i2s_2ch
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_slave_pdm_en
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_master_i2s_en
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_master_i2s_2ch
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_i2s_master_clk
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_i2s_slave_clk
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_pdm_clk
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_i2s_pdm_clk
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_i2s_master_ws
add wave -noupdate -group i2s_top /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/s_i2s_slave_ws
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/rstn_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/dft_test_mode_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/dft_cg_enable_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/pdm_clk_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/slave_clk_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/slave_ws_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/master_clk_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/master_ws_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/pad_pdm_clk_o
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/pad_slave_sd0_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/pad_slave_sd1_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/pad_master_sd0_o
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/pad_master_sd1_o
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_slave_en_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_master_en_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_slave_dsp_en_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_slave_dsp_setup_time_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_slave_dsp_mode_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_slave_dsp_offset_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_master_dsp_en_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_master_dsp_setup_time_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_master_dsp_mode_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_master_dsp_offset_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_rx_continuous_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_slave_i2s_lsb_first_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_slave_i2s_2ch_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_slave_i2s_bits_word_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_slave_i2s_words_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_slave_pdm_en_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_slave_pdm_mode_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_slave_pdm_decimation_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_slave_pdm_shift_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_master_i2s_lsb_first_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_master_i2s_2ch_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_master_i2s_bits_word_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/cfg_master_i2s_words_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/fifo_rx_data_o
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/fifo_rx_data_valid_o
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/fifo_rx_data_ready_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/fifo_tx_data_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/fifo_tx_data_valid_i
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/fifo_tx_data_ready_o
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/s_pdm_fifo_data
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/s_pdm_fifo_data_valid
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/s_pdm_fifo_data_ready
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/s_i2s_slv_fifo_data
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/s_i2s_slv_fifo_data_valid
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/s_i2s_slv_fifo_data_ready
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/s_i2s_slv_en
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/s_i2s_slv_dsp_en
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/s_i2s_mst_en
add wave -noupdate -group i2s_txrx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/s_i2s_mst_dsp_en
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/sck_i
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/rstn_i
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/i2s_ch0_o
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/i2s_ch1_o
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/i2s_ws_i
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/fifo_data_i
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/fifo_data_valid_i
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/fifo_data_ready_o
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/fifo_err_o
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/cfg_en_i
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/cfg_2ch_i
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/cfg_num_bits_i
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/cfg_num_word_i
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/cfg_lsb_first_i
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/cfg_master_dsp_mode_i
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/cfg_master_dsp_offset_i
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/r_shiftreg_ch0
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/r_shiftreg_ch1
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/s_shiftreg_ch0
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/s_shiftreg_ch1
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/r_shiftreg_shadow
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/s_shiftreg_shadow
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/data_ready
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/s_sample_sr0
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/s_sample_sr1
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/s_sample_swd
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/set_offset
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/en_offset
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/clear_offset
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/check_offset
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/r_count_bit
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/r_count_offset
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/s_word_done
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/s_word_done_pre
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/state
add wave -noupdate -group i2s_dsp_tx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_master/next_state
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/sck_i
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/rstn_i
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/i2s_ch0_i
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/i2s_ch1_i
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/i2s_ws_i
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/fifo_data_o
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/fifo_data_valid_o
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/fifo_data_ready_i
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/fifo_err_o
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_en_i
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_2ch_i
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_num_bits_i
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_num_word_i
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_lsb_first_i
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_rx_continuous_i
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_slave_dsp_mode_i
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_slave_dsp_offset_i
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_shiftreg_ch0
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_shiftreg_ch1
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_shiftreg_ch0_shadow
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_shiftreg_ch1_shadow
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_count_offset
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_count_bit
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/start
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/set_counter
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_ch0_valid
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_ch1_valid
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/state
add wave -noupdate -group i2s_dsp_rx_channel /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/next_state
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/sck_i
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/rstn_i
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/i2s_ch0_i
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/i2s_ch1_i
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/i2s_ws_i
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/fifo_data_o
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/fifo_data_valid_o
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/fifo_data_ready_i
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/fifo_err_o
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/cfg_en_i
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/cfg_2ch_i
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/cfg_num_bits_i
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/cfg_num_word_i
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/cfg_lsb_first_i
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/cfg_rx_continuous_i
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/cfg_slave_dsp_mode_i
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/cfg_slave_dsp_offset_i
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/r_shiftreg_ch0
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/r_shiftreg_ch1
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/r_shiftreg_ch0_shadow
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/r_shiftreg_ch1_shadow
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/r_count_offset
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/r_count_bit
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/start
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/set_counter
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/r_ch0_valid
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/r_ch1_valid
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/state
add wave -noupdate -group generic_rx_slave /tb_pulp/genblk6/genblk2/generic_dsp_slave_0/next_state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ms
update
WaveRestoreZoom {0 ps} {711 ps}
