onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/sys_clk_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/per_clk_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/dft_cg_enable_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/HRESETn
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PADDR
add wave -noupdate -group i_udmacore -radix hexadecimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PWDATA
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PWRITE
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PSEL
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PENABLE
add wave -noupdate -group i_udmacore -radix hexadecimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PRDATA
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PREADY
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/PSLVERR
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/event_valid_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/event_data_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/event_ready_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/event_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_per_clk_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_sys_clk_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_data_to_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_addr_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_rwn_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_data_from_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_valid_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/periph_ready_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_l2_req_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_l2_gnt_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_l2_addr_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_l2_be_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_l2_wdata_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_l2_req_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_l2_gnt_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_l2_addr_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_l2_rdata_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_l2_rvalid_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/stream_data_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/stream_datasize_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/stream_valid_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/stream_sot_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/stream_eot_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/stream_ready_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_valid_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_data_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_datasize_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_destination_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_ready_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_events_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_en_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_pending_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_curr_addr_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_bytes_left_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_cfg_startaddr_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_cfg_size_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_cfg_continuous_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_cfg_en_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_cfg_stream_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_cfg_stream_id_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_lin_cfg_clr_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_addr_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_datasize_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_destination_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_stream_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_stream_id_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_sot_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_eot_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_valid_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_data_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/rx_ext_ready_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_req_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_gnt_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_valid_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_data_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_ready_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_datasize_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_destination_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_events_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_en_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_pending_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_curr_addr_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_bytes_left_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_cfg_startaddr_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_cfg_size_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_cfg_continuous_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_cfg_en_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_lin_cfg_clr_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_req_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_datasize_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_destination_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_addr_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_gnt_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_valid_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_data_o
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/tx_ext_ready_i
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ch_req
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ch_addr
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ch_datasize
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ch_gnt
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ch_valid
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ch_data
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ch_ready
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_cfg_en
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_cfg_addr
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_cfg_buffsize
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_cfg_datasize
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_req
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_datasize
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_dest
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_addr
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_gnt
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_valid
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_data
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_ready
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_tx_ext_events
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_data_to
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_addr
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_rwn
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_data_from
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_valid
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_ready
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_ready_from_cgunit
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_periph_data_from_cgunit
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_cg_value
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_clk_core
add wave -noupdate -group i_udmacore /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/s_clk_core_en
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/clk_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/periph_clk_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/rstn_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_data_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_addr_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_valid_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rwn_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_data_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_ready_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_startaddr_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_size_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_datasize_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_continuous_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_en_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_clr_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_en_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_pending_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_curr_addr_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_rx_bytes_left_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_startaddr_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_size_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_datasize_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_continuous_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_en_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_clr_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_en_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_pending_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_curr_addr_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_tx_bytes_left_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_clk_en_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_clk_en_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_pdm_clk_en_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_dsp_en_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_dsp_setup_time_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_dsp_mode_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_dsp_offset_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_sel_num_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_sel_ext_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_sel_num_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_sel_ext_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_i2s_en_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_i2s_lsb_first_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_i2s_2ch_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_i2s_bits_word_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_i2s_words_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_pdm_en_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_pdm_mode_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_pdm_decimation_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_pdm_shift_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_i2s_en_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_i2s_lsb_first_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_i2s_2ch_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_i2s_bits_word_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_i2s_words_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_gen_clk_en_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_gen_clk_en_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_slave_gen_clk_div_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_gen_clk_en_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_gen_clk_en_i
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_master_gen_clk_div_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_rx_startaddr
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_rx_size
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_rx_datasize
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_rx_continuous
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_rx_en
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_rx_clr
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_tx_startaddr
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_tx_size
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_tx_datasize
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_tx_continuous
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_tx_en
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_tx_clr
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_clk_en
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_clk_en
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_master_clk_en
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_slave_clk_en
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_sel_num
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_sel_ext
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_sel_num
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_sel_ext
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_master_sel_num
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_master_sel_ext
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_slave_sel_num
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_slave_sel_ext
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_i2s_en
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_i2s_lsb_first
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_i2s_2ch
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_i2s_bits_word
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_i2s_words
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_pdm_en
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_pdm_mode
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_pdm_decimation
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_pdm_shift
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_dsp_en
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_dsp_setup_time
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_dsp_mode
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_dsp_offset
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_i2s_en
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_i2s_lsb_first
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_i2s_2ch
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_i2s_bits_word
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_i2s_words
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_common_gen_clk_div
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_slave_gen_clk_div
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_master_gen_clk_div
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_common_gen_clk_div
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_slave_gen_clk_div
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_master_gen_clk_div
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_pdm_clk_en
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_per_pdm_clk_en
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/s_wr_addr
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/s_rd_addr
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/s_update_clk
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/r_update_clk
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/cfg_update_clk_o
add wave -noupdate -group i2s_registers /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/u_reg_if/s_update
add wave -noupdate -group i2s_clk_master_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/clk_i
add wave -noupdate -group i2s_clk_master_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/rstn_i
add wave -noupdate -group i2s_clk_master_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/test_mode_i
add wave -noupdate -group i2s_clk_master_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/sck_o
add wave -noupdate -group i2s_clk_master_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/cfg_clk_en_i
add wave -noupdate -group i2s_clk_master_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/cfg_clk_en_o
add wave -noupdate -group i2s_clk_master_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/cfg_div_i
add wave -noupdate -group i2s_clk_master_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/r_counter
add wave -noupdate -group i2s_clk_master_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/r_clk
add wave -noupdate -group i2s_clk_master_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/r_sampled_config
add wave -noupdate -group i2s_clk_master_gen0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen0/r_clock_en
add wave -noupdate -group i2s_clk_slave_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/clk_i
add wave -noupdate -group i2s_clk_slave_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/rstn_i
add wave -noupdate -group i2s_clk_slave_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/test_mode_i
add wave -noupdate -group i2s_clk_slave_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/sck_o
add wave -noupdate -group i2s_clk_slave_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/cfg_clk_en_i
add wave -noupdate -group i2s_clk_slave_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/cfg_clk_en_o
add wave -noupdate -group i2s_clk_slave_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/cfg_div_i
add wave -noupdate -group i2s_clk_slave_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/r_counter
add wave -noupdate -group i2s_clk_slave_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/r_clk
add wave -noupdate -group i2s_clk_slave_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/r_sampled_config
add wave -noupdate -group i2s_clk_slave_gen1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_clkgen1/r_clock_en
add wave -noupdate -group i2s_ws_dsp_slave_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_slave_gen/sck_i
add wave -noupdate -group i2s_ws_dsp_slave_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_slave_gen/rstn_i
add wave -noupdate -group i2s_ws_dsp_slave_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_slave_gen/cfg_ws_en_i
add wave -noupdate -group i2s_ws_dsp_slave_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_slave_gen/cfg_num_bits_i
add wave -noupdate -group i2s_ws_dsp_slave_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_slave_gen/cfg_num_words_i
add wave -noupdate -group i2s_ws_dsp_slave_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_slave_gen/cfg_dsp_setup_time_i
add wave -noupdate -group i2s_ws_dsp_slave_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_slave_gen/cfg_dsp_mode_i
add wave -noupdate -group i2s_ws_dsp_slave_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_slave_gen/ws_o
add wave -noupdate -group i2s_ws_dsp_slave_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_slave_gen/limit
add wave -noupdate -group i2s_ws_dsp_slave_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_slave_gen/state
add wave -noupdate -group i2s_ws_dsp_slave_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_slave_gen/next_state
add wave -noupdate -group i2s_ws_dsp_slave_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_slave_gen/count
add wave -noupdate -group i2s_ws_dsp_slave_gen /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_clkws_gen/i_ws_dsp_slave_gen/set
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/sck_i
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/rstn_i
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/i2s_ch0_i
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/i2s_ch1_i
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/i2s_ws_i
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/fifo_data_o
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/fifo_data_valid_o
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/fifo_data_ready_i
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/fifo_err_o
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_en_i
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_2ch_i
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_num_bits_i
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_num_word_i
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_lsb_first_i
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_rx_continuous_i
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_slave_dsp_mode_i
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/cfg_slave_dsp_offset_i
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_shiftreg_ch0
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_shiftreg_ch1
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_shiftreg_ch0_shadow
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_shiftreg_ch1_shadow
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_count_offset
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_count_bit
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/start
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/set_counter
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_ch0_valid
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/r_ch1_valid
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/state
add wave -noupdate -group i2s_dsp_slave_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_i2s_udma/i_i2s_txrx/i_i2s_dsp_slave/next_state
add wave -noupdate -group mic_0 /tb_pulp/genblk6/genblk3/mic_0/data
add wave -noupdate -group mic_0 /tb_pulp/genblk6/genblk3/mic_0/lsb_first
add wave -noupdate -group mic_0 /tb_pulp/genblk6/genblk3/mic_0/ws
add wave -noupdate -group mic_0 /tb_pulp/genblk6/genblk3/mic_0/bclk
add wave -noupdate -group mic_0 /tb_pulp/genblk6/genblk3/mic_0/dout
add wave -noupdate -group mic_0 /tb_pulp/genblk6/genblk3/mic_0/wso
add wave -noupdate -group mic_0 /tb_pulp/genblk6/genblk3/mic_0/state
add wave -noupdate -group mic_0 /tb_pulp/genblk6/genblk3/mic_0/next_state
add wave -noupdate -group mic_0 /tb_pulp/genblk6/genblk3/mic_0/count
add wave -noupdate -group mic_0 /tb_pulp/genblk6/genblk3/mic_0/set
add wave -noupdate -group mic_0 /tb_pulp/genblk6/genblk3/mic_0/tristate
add wave -noupdate -group mic_1 /tb_pulp/genblk6/genblk3/mic_1/data
add wave -noupdate -group mic_1 /tb_pulp/genblk6/genblk3/mic_1/lsb_first
add wave -noupdate -group mic_1 /tb_pulp/genblk6/genblk3/mic_1/ws
add wave -noupdate -group mic_1 /tb_pulp/genblk6/genblk3/mic_1/bclk
add wave -noupdate -group mic_1 /tb_pulp/genblk6/genblk3/mic_1/dout
add wave -noupdate -group mic_1 /tb_pulp/genblk6/genblk3/mic_1/wso
add wave -noupdate -group mic_1 /tb_pulp/genblk6/genblk3/mic_1/state
add wave -noupdate -group mic_1 /tb_pulp/genblk6/genblk3/mic_1/next_state
add wave -noupdate -group mic_1 /tb_pulp/genblk6/genblk3/mic_1/count
add wave -noupdate -group mic_1 /tb_pulp/genblk6/genblk3/mic_1/set
add wave -noupdate -group mic_1 /tb_pulp/genblk6/genblk3/mic_1/tristate
add wave -noupdate -group mic_2 /tb_pulp/genblk6/genblk3/mic_2/data
add wave -noupdate -group mic_2 /tb_pulp/genblk6/genblk3/mic_2/lsb_first
add wave -noupdate -group mic_2 /tb_pulp/genblk6/genblk3/mic_2/ws
add wave -noupdate -group mic_2 /tb_pulp/genblk6/genblk3/mic_2/bclk
add wave -noupdate -group mic_2 /tb_pulp/genblk6/genblk3/mic_2/dout
add wave -noupdate -group mic_2 /tb_pulp/genblk6/genblk3/mic_2/wso
add wave -noupdate -group mic_2 /tb_pulp/genblk6/genblk3/mic_2/state
add wave -noupdate -group mic_2 /tb_pulp/genblk6/genblk3/mic_2/next_state
add wave -noupdate -group mic_2 /tb_pulp/genblk6/genblk3/mic_2/count
add wave -noupdate -group mic_2 /tb_pulp/genblk6/genblk3/mic_2/set
add wave -noupdate -group mic_2 /tb_pulp/genblk6/genblk3/mic_2/tristate
add wave -noupdate -group mic_3 /tb_pulp/genblk6/genblk3/mic_3/data
add wave -noupdate -group mic_3 /tb_pulp/genblk6/genblk3/mic_3/lsb_first
add wave -noupdate -group mic_3 /tb_pulp/genblk6/genblk3/mic_3/ws
add wave -noupdate -group mic_3 /tb_pulp/genblk6/genblk3/mic_3/bclk
add wave -noupdate -group mic_3 /tb_pulp/genblk6/genblk3/mic_3/dout
add wave -noupdate -group mic_3 /tb_pulp/genblk6/genblk3/mic_3/wso
add wave -noupdate -group mic_3 /tb_pulp/genblk6/genblk3/mic_3/state
add wave -noupdate -group mic_3 /tb_pulp/genblk6/genblk3/mic_3/next_state
add wave -noupdate -group mic_3 /tb_pulp/genblk6/genblk3/mic_3/count
add wave -noupdate -group mic_3 /tb_pulp/genblk6/genblk3/mic_3/set
add wave -noupdate -group mic_3 /tb_pulp/genblk6/genblk3/mic_3/tristate
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 618
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ms
update
WaveRestoreZoom {0 ps} {345 ps}
