onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_0
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_1
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_2
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_3
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_4
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_5
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_6
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_7
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_8
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_9
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_10
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_11
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_12
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_13
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_14
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_15
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_16
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_17
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_18
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_19
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_20
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_21
add wave -noupdate -group ext_pad /tb_pulp/w_gpio_22
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/pad_mux_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/pad_cfg_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/pad_cfg_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/gpio_out_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/gpio_in_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/gpio_dir_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/gpio_cfg_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/uart_tx_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/uart_rx_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2c_scl_out_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2c_scl_in_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2c_scl_oe_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2c_sda_out_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2c_sda_in_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2c_sda_oe_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_slave_sd0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_slave_sd1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_slave_ws_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_slave_ws_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_slave_ws_oe
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_slave_sck_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_slave_sck_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_slave_sck_oe
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_master_sd0_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_master_sd1_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_master_ws_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_master_ws_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_master_ws_oe
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_master_sck_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_master_sck_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_master_sck_oe
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/hyper_cs_ni
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/hyper_ck_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/hyper_ck_ni
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/hyper_rwds_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/hyper_rwds_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/hyper_rwds_oe_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/hyper_dq_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/hyper_dq_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/hyper_dq_oe_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/hyper_reset_no
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/spi_clk_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/spi_csn_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/spi_oen_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/spi_sdo_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/spi_sdi_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/spis_clk_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/spis_csn_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/spis_sdi0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/spis_sdi1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/timer0_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/timer1_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/timer2_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/timer3_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_qspi_sdio0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_qspi_sdio1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_qspi_sdio2_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_qspi_sdio3_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_qspi_csn0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_qspi_sck_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_spim_sdio0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_spim_sdio1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_spim_csn0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_spim_csn1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_spim_sck_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_spis_sck_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_spis_csn0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_spis_sdio0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_spis_sdio1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_uart_rx_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_uart_tx_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_i2c0_sda_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_i2c0_scl_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_i2s0_sck_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_i2s0_ws_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_i2s0_sdi0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_i2s0_sdi1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_i2s1_sck_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_i2s1_ws_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_i2s1_sdi0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_i2s1_sdi1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_hyper_cs0n_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_hyper_cs1n_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_hyper_ck_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_hyper_ckn_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_hyper_rwds0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_hyper_rwds1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_hyper_dq0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_hyper_dq1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/out_hyper_resetn_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_qspi_sdio0_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_qspi_sdio1_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_qspi_sdio2_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_qspi_sdio3_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_qspi_csn0_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_qspi_sck_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_spim_sdio0_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_spim_sdio1_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_spim_csn0_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_spim_csn1_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_spim_sck_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_spis_sck_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_spis_csn_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_spis_sdio0_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_spis_sdio1_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_uart_rx_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_uart_tx_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_i2c0_sda_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_i2c0_scl_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_i2s0_sck_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_i2s0_ws_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_i2s0_sdi0_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_i2s0_sdi1_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_i2s1_sck_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_i2s1_ws_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_i2s1_sdi0_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_i2s1_sdi1_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_hyper_cs0n_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_hyper_cs1n_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_hyper_ck_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_hyper_ckn_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_hyper_rwds0_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_hyper_rwds1_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_hyper_dq0_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_hyper_dq1_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/in_hyper_resetn_i
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_qspi_sdio0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_qspi_sdio1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_qspi_sdio2_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_qspi_sdio3_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_qspi_csn0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_qspi_sck_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_spim_sdio0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_spim_sdio1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_spim_csn0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_spim_csn1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_spim_sck_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_spis_sck_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_spis_csn0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_spis_sdio0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_spis_sdio1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_uart_rx_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_uart_tx_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_i2c0_sda_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_i2c0_scl_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_i2s0_sck_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_i2s0_ws_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_i2s0_sdi0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_i2s0_sdi1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_i2s1_sck_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_i2s1_ws_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_i2s1_sdi0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_i2s1_sdi1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_hyper_cs0n_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_hyper_cs1n_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_hyper_ck_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_hyper_ckn_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_hyper_rwds0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_hyper_rwds1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_hyper_dq0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_hyper_dq1_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/oe_hyper_resetn_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/s_alt0
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/s_alt1
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/s_alt2
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/s_alt3
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_master_sd0_o
add wave -noupdate -group pad_control /tb_pulp/i_dut/safe_domain_i/pad_control_i/i2s_master_sd1_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_cfg_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/ref_clk_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/rstn_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/jtag_tck_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/jtag_tdi_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/jtag_tdo_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/jtag_tms_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/jtag_trst_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_qspi_sdio0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_qspi_sdio1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_qspi_sdio2_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_qspi_sdio3_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_qspi_csn0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_qspi_sck_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_spim_sdio0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_spim_sdio1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_spim_csn0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_spim_csn1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_spim_sck_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_spis_sck_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_spis_csn0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_spis_sdio0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_spis_sdio1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_i2s0_sck_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_i2s0_ws_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_i2s0_sdi0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_i2s0_sdi1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_i2s1_sck_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_i2s1_ws_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_i2s1_sdi0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_i2s1_sdi1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_hyper_cs0n_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_hyper_cs1n_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_hyper_ck_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_hyper_ckn_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_hyper_rwds0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_hyper_rwds1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_hyper_dq0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_hyper_dq1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_hyper_resetn_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_i2c0_sda_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_i2c0_scl_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_uart_rx_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/oe_uart_tx_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_qspi_sdio0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_qspi_sdio1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_qspi_sdio2_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_qspi_sdio3_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_qspi_csn0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_qspi_sck_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_spim_sdio0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_spim_sdio1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_spim_csn1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_spim_csn0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_spim_sck_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_spis_sck_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_spis_csn0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_spis_sdio0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_spis_sdio1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_i2s0_sck_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_i2s0_ws_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_i2s0_sdi0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_i2s0_sdi1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_i2s1_sck_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_i2s1_ws_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_i2s1_sdi0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_i2s1_sdi1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_hyper_cs0n_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_hyper_cs1n_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_hyper_ck_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_hyper_ckn_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_hyper_rwds0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_hyper_rwds1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_hyper_dq0_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_hyper_dq1_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_hyper_resetn_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_i2c0_sda_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_i2c0_scl_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_uart_rx_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/out_uart_tx_i
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_qspi_sdio0_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_qspi_sdio1_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_qspi_sdio2_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_qspi_sdio3_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_qspi_csn0_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_qspi_sck_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_spim_sdio0_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_spim_sdio1_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_spim_csn1_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_spim_csn0_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_spim_sck_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_spis_sck_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_spis_csn0_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_spis_sdio0_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_spis_sdio1_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_i2s0_sck_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_i2s0_ws_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_i2s0_sdi0_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_i2s0_sdi1_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_i2s1_sck_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_i2s1_ws_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_i2s1_sdi0_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_i2s1_sdi1_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_hyper_cs0n_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_hyper_cs1n_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_hyper_ck_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_hyper_ckn_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_hyper_rwds0_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_hyper_rwds1_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_hyper_dq0_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_hyper_dq1_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_hyper_resetn_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_i2c0_sda_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_i2c0_scl_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_uart_rx_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/in_uart_tx_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/bootsel_o
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_qspi_sdio0
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_qspi_sdio1
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_qspi_sdio2
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_qspi_sdio3
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_qspi_csn0
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_qspi_sck
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_spim_sdio0
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_spim_sdio1
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_spim_csn0
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_spim_csn1
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_spim_sck
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_spis_sck
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_spis_cs
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_spis_sdio0
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_spis_sdio1
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_i2ss_sck
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_i2ss_ws
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_i2ss_sdi0
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_i2ss_sdi1
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_i2sm_sck
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_i2sm_ws
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_i2sm_sdi0
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_i2sm_sdi1
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_i2c0_sda
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_i2c0_scl
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_uart_rx
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_uart_tx
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_hyper_dq0
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_hyper_dq1
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_hyper_ck
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_hyper_ckn
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_hyper_csn0
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_hyper_csn1
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_hyper_rwds0
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_hyper_rwds1
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_hyper_reset
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_reset_n
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_bootsel0
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_bootsel1
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_jtag_tck
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_jtag_tdi
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_jtag_tdo
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_jtag_tms
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_jtag_trst
add wave -noupdate -group pad_frame /tb_pulp/i_dut/pad_frame_i/pad_xtal_in
add wave -noupdate -group padinst_qspi_sdio0 /tb_pulp/i_dut/pad_frame_i/padinst_qspi_sdio0/OEN
add wave -noupdate -group padinst_qspi_sdio0 /tb_pulp/i_dut/pad_frame_i/padinst_qspi_sdio0/I
add wave -noupdate -group padinst_qspi_sdio0 /tb_pulp/i_dut/pad_frame_i/padinst_qspi_sdio0/O
add wave -noupdate -group padinst_qspi_sdio0 /tb_pulp/i_dut/pad_frame_i/padinst_qspi_sdio0/PEN
add wave -noupdate -group padinst_qspi_sdio0 /tb_pulp/i_dut/pad_frame_i/padinst_qspi_sdio0/PAD
add wave -noupdate -group padinst_qspi_sdio0 /tb_pulp/i_dut/pad_frame_i/padinst_qspi_sdio0/PAD_wi
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {6968323276 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 158
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ms
update
WaveRestoreZoom {0 ps} {31164170100 ps}
